dist: trusty
sudo: false
language: go
go:
  - 1.9.1
os:
  - linux
  - osx

before_install:
- openssl aes-256-cbc -K $encrypted_f2f8be5bc079_key -iv $encrypted_f2f8be5bc079_iv 
  -in gogetcookie.sh.enc -out scripts/gogetcookie.sh -d

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh
- go get github.com/golang/dep/cmd/dep
- dep ensure

script:
- make test
- make vet

matrix:
  fast_finish: true
  allow_failures:
  - go: tip
